# =============================================================================
# Odoo Droplet Template — Makefile
# =============================================================================
# Template lifecycle: init → generate → tf-init → tf-apply → deploy
#
# Configuration is driven by instance.conf (generated by setup.sh).
# Secrets (DIGITALOCEAN_TOKEN, AWS_ACCESS_KEY_ID, etc.) come from .env.
# =============================================================================

.DEFAULT_GOAL := help

# Source .env if it exists (DO tokens, AWS credentials)
-include .env
export

# Source instance.conf if it exists (project-specific values)
-include instance.conf
export

# ---------------------------------------------------------------------------
# Configuration — defaults and derived values
# ---------------------------------------------------------------------------
SSH_PORT     ?= 9292
SSH_USER     ?= deploy
SSH_KEY      ?= ~/.ssh/id_ed25519
ALIAS_DOMAIN ?=
ADDON_PATH   ?=

# Derive from instance.conf values
DOMAIN       ?= $(PRIMARY_DOMAIN)
CERT_EMAIL   ?= $(ADMIN_EMAIL)

# Derived paths
VOLUME_MOUNT  = /mnt/$(PROJECT_NAME)-data
RCLONE_REMOTE = spaces:$(BACKUP_BUCKET)

# Resolve droplet IP from terraform output if not explicitly set
DROPLET_IP   ?= $(shell cd infra && AWS_ACCESS_KEY_ID=$(AWS_ACCESS_KEY_ID) AWS_SECRET_ACCESS_KEY=$(AWS_SECRET_ACCESS_KEY) terraform output -raw droplet_ip 2>/dev/null)

SSH_OPTS     := -o StrictHostKeyChecking=accept-new -i $(SSH_KEY)
SSH_CMD      := ssh $(SSH_OPTS) -p $(SSH_PORT) $(SSH_USER)@$(DROPLET_IP)
SCP_CMD      := scp $(SSH_OPTS) -P $(SSH_PORT)

REMOTE_DIR   := /tmp/odoo-setup

# ---------------------------------------------------------------------------
# Setup — template initialization and generation
# ---------------------------------------------------------------------------

.PHONY: init
init: ## Run setup.sh to initialize a new instance (creates instance.conf)
	./setup.sh

.PHONY: generate
generate: ## Run generate.sh to render configs from instance.conf
	./generate.sh

.PHONY: validate
validate: ## Check prerequisites: instance.conf, backend.tf, config/.env, terraform validate
	@[ -f instance.conf ] || { echo "ERROR: instance.conf not found — run 'make init' first"; exit 1; }
	@[ -f infra/backend.tf ] || { echo "ERROR: infra/backend.tf not found — run 'make generate' first"; exit 1; }
	@[ -f config/.env ] || { echo "ERROR: config/.env not found — copy config/.env.example and fill in secrets"; exit 1; }
	cd infra && terraform validate
	@echo "Validation passed."

# ---------------------------------------------------------------------------
# Terraform
# ---------------------------------------------------------------------------

.PHONY: tf-init
tf-init: ## Initialize Terraform backend and providers
	cd infra && terraform init

.PHONY: tf-plan
tf-plan: ## Preview infrastructure changes
	cd infra && terraform plan

.PHONY: tf-apply
tf-apply: ## Provision/update DigitalOcean infrastructure
	cd infra && terraform apply

.PHONY: tf-output
tf-output: ## Show Terraform outputs (droplet IP, volume path, etc.)
	cd infra && terraform output

.PHONY: tf-destroy
tf-destroy: ## Destroy all infrastructure (interactive confirmation)
	cd infra && terraform destroy

# ---------------------------------------------------------------------------
# Deployment — upload and phased script execution
# ---------------------------------------------------------------------------

.PHONY: upload
upload: ## Upload config/ and scripts/ to droplet
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set and terraform output unavailable"; exit 1; }
	$(SSH_CMD) "sudo rm -rf $(REMOTE_DIR) && mkdir -p $(REMOTE_DIR)"
	$(SCP_CMD) -r config/ $(SSH_USER)@$(DROPLET_IP):$(REMOTE_DIR)/
	$(SCP_CMD) -r scripts/ $(SSH_USER)@$(DROPLET_IP):$(REMOTE_DIR)/
	@echo "Uploaded to $(SSH_USER)@$(DROPLET_IP):$(REMOTE_DIR)"

.PHONY: deploy-phase1
deploy-phase1: ## Run 01-harden-host.sh on droplet (requires SSH_USER=root for first run)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	$(SSH_CMD) "sudo bash $(REMOTE_DIR)/scripts/01-harden-host.sh"

.PHONY: deploy-phase2
deploy-phase2: ## Run 02-install-docker.sh on droplet
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	$(SSH_CMD) "sudo bash $(REMOTE_DIR)/scripts/02-install-docker.sh"

.PHONY: deploy-phase3
deploy-phase3: ## Run 03-deploy-stack.sh on droplet (uses VOLUME_MOUNT from instance.conf)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	$(SSH_CMD) "sudo -E VOLUME_MOUNT=$(VOLUME_MOUNT) bash $(REMOTE_DIR)/scripts/03-deploy-stack.sh"

.PHONY: deploy-phase4
deploy-phase4: ## Run 04-setup-nginx.sh on droplet (uses DOMAIN and CERT_EMAIL from instance.conf)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	@[ -n "$(DOMAIN)" ] || { echo "ERROR: DOMAIN not set — check PRIMARY_DOMAIN in instance.conf"; exit 1; }
	@[ -n "$(CERT_EMAIL)" ] || { echo "ERROR: CERT_EMAIL not set — check ADMIN_EMAIL in instance.conf"; exit 1; }
	$(SSH_CMD) "sudo bash $(REMOTE_DIR)/scripts/04-setup-nginx.sh $(DOMAIN) $(CERT_EMAIL)"

.PHONY: deploy-phase5
deploy-phase5: ## Run 05-setup-backups.sh on droplet (uses VOLUME_MOUNT and RCLONE_REMOTE)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	$(SSH_CMD) "sudo -E VOLUME_MOUNT=$(VOLUME_MOUNT) RCLONE_REMOTE=$(RCLONE_REMOTE) bash $(REMOTE_DIR)/scripts/05-setup-backups.sh"

.PHONY: deploy
deploy: upload deploy-phase1 deploy-phase2 deploy-phase3 deploy-phase4 deploy-phase5 ## Full deployment pipeline: upload → phase1–5

# ---------------------------------------------------------------------------
# Day-2 Operations
# ---------------------------------------------------------------------------

.PHONY: set-domain
set-domain: upload ## Change primary domain (requires DOMAIN, CERT_EMAIL; optional ALIAS_DOMAIN)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	@[ -n "$(DOMAIN)" ] || { echo "ERROR: DOMAIN not set (e.g., make set-domain DOMAIN=portal.example.com CERT_EMAIL=admin@example.com)"; exit 1; }
	@[ -n "$(CERT_EMAIL)" ] || { echo "ERROR: CERT_EMAIL not set"; exit 1; }
	$(SSH_CMD) "sudo bash $(REMOTE_DIR)/scripts/ops/set-domain.sh $(DOMAIN) $(CERT_EMAIL) $(ALIAS_DOMAIN)"

.PHONY: deploy-addon
deploy-addon: upload ## Deploy custom Odoo module (requires ADDON_PATH=local/path/to/module)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	@[ -n "$(ADDON_PATH)" ] || { echo "ERROR: ADDON_PATH not set (e.g., make deploy-addon ADDON_PATH=../my-project/odoo_modules/my_module)"; exit 1; }
	@[ -d "$(ADDON_PATH)" ] || { echo "ERROR: $(ADDON_PATH) is not a directory"; exit 1; }
	@echo "Uploading $(ADDON_PATH) to droplet..."
	$(SCP_CMD) -r $(ADDON_PATH) $(SSH_USER)@$(DROPLET_IP):/opt/odoo/custom-addons/
	@echo "Running deploy-addon.sh on droplet..."
	$(SSH_CMD) "sudo bash $(REMOTE_DIR)/scripts/ops/deploy-addon.sh $$(basename $(ADDON_PATH))"

.PHONY: ssh
ssh: ## Open SSH session to droplet
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	$(SSH_CMD)

.PHONY: status
status: ## Check remote service status (Docker, Odoo, Nginx)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	@echo "--- Docker ---"
	$(SSH_CMD) "sudo docker compose -f /opt/odoo/docker-compose.yml ps" 2>/dev/null || echo "(not deployed yet)"
	@echo "--- Nginx ---"
	$(SSH_CMD) "sudo systemctl is-active nginx" 2>/dev/null || echo "(not installed yet)"
	@echo "--- UFW ---"
	$(SSH_CMD) "sudo ufw status numbered" 2>/dev/null || echo "(not configured yet)"

.PHONY: logs
logs: ## Tail Odoo container logs
	$(SSH_CMD) "sudo docker compose -f /opt/odoo/docker-compose.yml logs -f --tail=50 odoo"

.PHONY: logs-db
logs-db: ## Tail PostgreSQL container logs
	$(SSH_CMD) "sudo docker compose -f /opt/odoo/docker-compose.yml logs -f --tail=50 postgres"

.PHONY: logs-nginx
logs-nginx: ## Tail Nginx access and error logs
	$(SSH_CMD) "sudo tail -f /var/log/nginx/odoo-access.log /var/log/nginx/odoo-error.log"

.PHONY: backup-now
backup-now: ## Trigger a manual backup on the droplet (uses VOLUME_MOUNT from instance.conf)
	@[ -n "$(DROPLET_IP)" ] || { echo "ERROR: DROPLET_IP not set"; exit 1; }
	$(SSH_CMD) "sudo -E VOLUME_MOUNT=$(VOLUME_MOUNT) bash /opt/odoo/scripts/06-backup-daily.sh"

# ---------------------------------------------------------------------------
# Testing
# ---------------------------------------------------------------------------

.PHONY: test
test: ## Run OdooKit test suite if odookit/ exists
	@if [ -d odookit ]; then \
		cd odookit && npm test; \
	else \
		echo "odookit/ not found."; \
		echo "To add OdooKit: clone or symlink your OdooKit project into odookit/"; \
		echo "  git clone <odookit-repo> odookit"; \
	fi

# ---------------------------------------------------------------------------
# Validation and linting
# ---------------------------------------------------------------------------

.PHONY: lint
lint: ## Shellcheck all deployment scripts
	shellcheck scripts/*.sh scripts/ops/*.sh setup.sh generate.sh

.PHONY: check
check: validate lint ## Run all local checks (validate + shellcheck)

# ---------------------------------------------------------------------------
# Cleanup
# ---------------------------------------------------------------------------

.PHONY: clean
clean: ## Remove generated files (keeps instance.conf)
	rm -f infra/backend.tf
	rm -f infra/terraform.tfvars
	rm -f config/.env
	rm -f config/odoo.conf
	rm -f config/nginx/odoo.conf
	rm -f config/nginx/odoo-pre-ssl.conf
	@echo "Generated files removed. instance.conf preserved."

.PHONY: nuke
nuke: clean ## Remove generated files AND instance.conf (full reset)
	rm -f instance.conf
	@echo "instance.conf removed. Run 'make init' to start fresh."

# ---------------------------------------------------------------------------
# Help
# ---------------------------------------------------------------------------

.PHONY: help
help: ## Show this help
	@grep -E '^[a-zA-Z0-9_-]+:.*?## .*$$' $(firstword $(MAKEFILE_LIST)) | \
		awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-18s\033[0m %s\n", $$1, $$2}'
